name: test
on:
  push:

jobs:

  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/matrix.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$TASKS"
  setup:
    uses: Chrismarsh/gha-testing/.github/workflows/setup.yml@main
    with:
      matrix: matrix

  on_push:
    needs: [matrix, setup]
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - run: |
          for x in $(find . -not -path '*/.*'  -not -path '.' -type d -maxdepth 1 | sed "s|^\./||")
          do
            cd $x
            for v in $(yq e '.sources | keys' conandata.yml | awk '{ print $NF }' | sed 's/\"//g')
            do
              echo "$x/$v"
            done
            cd ..
          done


  directory_diff:
    needs: [matrix, setup]
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: folder diff
        run: |
          for x in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u)
          do
            cd $x
            for v in $(yq e '.sources | keys' conandata.yml | awk '{ print $NF }' | sed 's/\"//g')
            do
              echo "$x/$v"
            done
            cd ..
          done
