name: Build changed
on:
  push:

jobs:

  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/matrix.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$TASKS"
  setup:
    needs: [matrix]
    runs-on: ${{ inputs.matrix.matrix.cfg.os }}
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install yq
        if: startsWith( inputs.matrix.matrix.cfg.os, 'macos' )
        run: |
          export PATH="$pythonLocation:$PATH"
          brew install yq

      - name: env linux
        if: startsWith( inputs.matrix.matrix.cfg.os, 'ubuntu' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_GCC_VERSIONS: ${{ inputs.matrix.matrix.cfg.version }}
          CC: gcc-${{ inputs.matrix.matrix.cfg.version }}
          CXX: g++-${{ inputs.matrix.matrix.cfg.version }}
          GFORTRAN_NAME: gfortran-${{ inputs.matrix.matrix.cfg.version }}

      - name: env macos
        if: startsWith( inputs.matrix.matrix.cfg.os, 'macos' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_APPLE_CLANG_VERSIONS: ${{ inputs.matrix.matrix.cfg.version }}
          GFORTRAN_NAME: gfortran-10


  directory_diff:
    needs: [matrix, setup]
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: folder diff
        run: |
          for x in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u)
          do
            cd $x
            for v in $(yq e '.sources | keys' conandata.yml | awk '{ print $NF }' | sed 's/\"//g')
            do
              echo "$x/$v"
            done
            cd ..
          done
