on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: matrix
jobs:
  setup:
    runs-on: ${{ inputs.matrix.matrix.cfg.os }}
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install yq
        if: startsWith( inputs.matrix.matrix.cfg.os, 'macos' )
        run: |
          export PATH="$pythonLocation:$PATH"
          brew install yq

      - name: env linux
        if: startsWith( inputs.matrix.matrix.cfg.os, 'ubuntu' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_GCC_VERSIONS: ${{ inputs.matrix.matrix.cfg.version }}
          CC: gcc-${{ inputs.matrix.matrix.cfg.version }}
          CXX: g++-${{ inputs.matrix.matrix.cfg.version }}
          GFORTRAN_NAME: gfortran-${{ inputs.matrix.matrix.cfg.version }}

      - name: env macos
        if: startsWith( inputs.matrix.matrix.cfg.os, 'macos' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_APPLE_CLANG_VERSIONS: ${{ inputs.matrix.matrix.cfg.version }}
          GFORTRAN_NAME: gfortran-10