on:
  workflow_call:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        fetch-depth: 0
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/matrix.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$TASKS"

  setup:
    needs: [matrix]
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install yq
        if: startsWith( matrix.cfg.os, 'macos' )
        run: |
          export PATH="$pythonLocation:$PATH"
          brew install yq

      - name: env linux
        if: startsWith( matrix.cfg.os, 'ubuntu' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_GCC_VERSIONS: ${{ matrix.cfg.version }}
          CC: gcc-${{ matrix.cfg.version }}
          CXX: g++-${{ matrix.cfg.version }}
          GFORTRAN_NAME: gfortran-${{ matrix.cfg.version }}

      - name: env macos
        if: startsWith( matrix.cfg.os, 'macos' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_APPLE_CLANG_VERSIONS: ${{ matrix.cfg.version }}
          GFORTRAN_NAME: gfortran-10